// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tradedtls.proto

package grpc.trade.proto;

public interface ReplyTradeDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trade.ReplyTradeDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 trade_dtls_no = 2;</code>
   */
  long getTradeDtlsNo();

  /**
   * <code>int64 trade_id = 3;</code>
   */
  long getTradeId();

  /**
   * <code>int64 product_id = 4;</code>
   */
  long getProductId();

  /**
   * <code>int64 lot_no = 5;</code>
   */
  long getLotNo();

  /**
   * <code>string product_cd = 6;</code>
   */
  java.lang.String getProductCd();
  /**
   * <code>string product_cd = 6;</code>
   */
  com.google.protobuf.ByteString
      getProductCdBytes();

  /**
   * <code>string product_name = 7;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string product_name = 7;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string mgt_product_name = 8;</code>
   */
  java.lang.String getMgtProductName();
  /**
   * <code>string mgt_product_name = 8;</code>
   */
  com.google.protobuf.ByteString
      getMgtProductNameBytes();

  /**
   * <code>string tax_kbn = 9;</code>
   */
  java.lang.String getTaxKbn();
  /**
   * <code>string tax_kbn = 9;</code>
   */
  com.google.protobuf.ByteString
      getTaxKbnBytes();

  /**
   * <code>string choices_alt_stock_item_row_cd = 10;</code>
   */
  java.lang.String getChoicesAltStockItemRowCd();
  /**
   * <code>string choices_alt_stock_item_row_cd = 10;</code>
   */
  com.google.protobuf.ByteString
      getChoicesAltStockItemRowCdBytes();

  /**
   * <code>string choices_alt_stock_item_col_cd = 11;</code>
   */
  java.lang.String getChoicesAltStockItemColCd();
  /**
   * <code>string choices_alt_stock_item_col_cd = 11;</code>
   */
  com.google.protobuf.ByteString
      getChoicesAltStockItemColCdBytes();

  /**
   * <code>string trade_product_mgt_id = 12;</code>
   */
  java.lang.String getTradeProductMgtId();
  /**
   * <code>string trade_product_mgt_id = 12;</code>
   */
  com.google.protobuf.ByteString
      getTradeProductMgtIdBytes();

  /**
   * <code>string trade_dtls_opt = 13;</code>
   */
  java.lang.String getTradeDtlsOpt();
  /**
   * <code>string trade_dtls_opt = 13;</code>
   */
  com.google.protobuf.ByteString
      getTradeDtlsOptBytes();

  /**
   * <code>string buy_opt_commission_txt = 14;</code>
   */
  java.lang.String getBuyOptCommissionTxt();
  /**
   * <code>string buy_opt_commission_txt = 14;</code>
   */
  com.google.protobuf.ByteString
      getBuyOptCommissionTxtBytes();

  /**
   * <code>string buy_opt_commission_txt_hist = 15;</code>
   */
  java.lang.String getBuyOptCommissionTxtHist();
  /**
   * <code>string buy_opt_commission_txt_hist = 15;</code>
   */
  com.google.protobuf.ByteString
      getBuyOptCommissionTxtHistBytes();

  /**
   * <code>int64 buy_opt_commission = 16;</code>
   */
  long getBuyOptCommission();

  /**
   * <code>int64 buy_opt_commission_edit = 17;</code>
   */
  long getBuyOptCommissionEdit();

  /**
   * <code>string gift_packing_type = 18;</code>
   */
  java.lang.String getGiftPackingType();
  /**
   * <code>string gift_packing_type = 18;</code>
   */
  com.google.protobuf.ByteString
      getGiftPackingTypeBytes();

  /**
   * <code>string gift_packing_type_edit = 19;</code>
   */
  java.lang.String getGiftPackingTypeEdit();
  /**
   * <code>string gift_packing_type_edit = 19;</code>
   */
  com.google.protobuf.ByteString
      getGiftPackingTypeEditBytes();

  /**
   * <code>int64 gift_commission = 20;</code>
   */
  long getGiftCommission();

  /**
   * <code>int64 gift_commission_edit = 21;</code>
   */
  long getGiftCommissionEdit();

  /**
   * <code>string gift_msg = 22;</code>
   */
  java.lang.String getGiftMsg();
  /**
   * <code>string gift_msg = 22;</code>
   */
  com.google.protobuf.ByteString
      getGiftMsgBytes();

  /**
   * <code>string gift_msg_edit = 23;</code>
   */
  java.lang.String getGiftMsgEdit();
  /**
   * <code>string gift_msg_edit = 23;</code>
   */
  com.google.protobuf.ByteString
      getGiftMsgEditBytes();

  /**
   * <code>string noshi_type = 24;</code>
   */
  java.lang.String getNoshiType();
  /**
   * <code>string noshi_type = 24;</code>
   */
  com.google.protobuf.ByteString
      getNoshiTypeBytes();

  /**
   * <code>string noshi_type_edit = 25;</code>
   */
  java.lang.String getNoshiTypeEdit();
  /**
   * <code>string noshi_type_edit = 25;</code>
   */
  com.google.protobuf.ByteString
      getNoshiTypeEditBytes();

  /**
   * <code>string noshi_presenter_name1 = 26;</code>
   */
  java.lang.String getNoshiPresenterName1();
  /**
   * <code>string noshi_presenter_name1 = 26;</code>
   */
  com.google.protobuf.ByteString
      getNoshiPresenterName1Bytes();

  /**
   * <code>string noshi_presenter_name1_edit = 27;</code>
   */
  java.lang.String getNoshiPresenterName1Edit();
  /**
   * <code>string noshi_presenter_name1_edit = 27;</code>
   */
  com.google.protobuf.ByteString
      getNoshiPresenterName1EditBytes();

  /**
   * <code>string noshi_presenter_name2 = 28;</code>
   */
  java.lang.String getNoshiPresenterName2();
  /**
   * <code>string noshi_presenter_name2 = 28;</code>
   */
  com.google.protobuf.ByteString
      getNoshiPresenterName2Bytes();

  /**
   * <code>string noshi_presenter_name2_edit = 29;</code>
   */
  java.lang.String getNoshiPresenterName2Edit();
  /**
   * <code>string noshi_presenter_name2_edit = 29;</code>
   */
  com.google.protobuf.ByteString
      getNoshiPresenterName2EditBytes();

  /**
   * <code>string noshi_presenter_name3 = 30;</code>
   */
  java.lang.String getNoshiPresenterName3();
  /**
   * <code>string noshi_presenter_name3 = 30;</code>
   */
  com.google.protobuf.ByteString
      getNoshiPresenterName3Bytes();

  /**
   * <code>string noshi_presenter_name3_edit = 31;</code>
   */
  java.lang.String getNoshiPresenterName3Edit();
  /**
   * <code>string noshi_presenter_name3_edit = 31;</code>
   */
  com.google.protobuf.ByteString
      getNoshiPresenterName3EditBytes();

  /**
   * <code>int64 tarde_dtls_dscnt_bfr = 32;</code>
   */
  long getTardeDtlsDscntBfr();

  /**
   * <code>int64 tarde_dtls_dscnt_amt = 33;</code>
   */
  long getTardeDtlsDscntAmt();

  /**
   * <code>int64 tarde_dtls_untprc = 34;</code>
   */
  long getTardeDtlsUntprc();

  /**
   * <code>int64 tarde_dtls_untprc_edit = 35;</code>
   */
  long getTardeDtlsUntprcEdit();

  /**
   * <code>int64 tarde_dtls_quantity = 36;</code>
   */
  long getTardeDtlsQuantity();

  /**
   * <code>int64 tarde_dtls_quantity_edit = 37;</code>
   */
  long getTardeDtlsQuantityEdit();

  /**
   * <code>int64 tarde_dtls_pt_rate = 38;</code>
   */
  long getTardeDtlsPtRate();

  /**
   * <code>int64 tarde_dtls_pt = 39;</code>
   */
  long getTardeDtlsPt();

  /**
   * <code>int64 tarde_dtls_amt_subtotal = 40;</code>
   */
  long getTardeDtlsAmtSubtotal();

  /**
   * <code>int64 commission_subtotal = 41;</code>
   */
  long getCommissionSubtotal();

  /**
   * <code>int32 tmsale_product_flg = 42;</code>
   */
  int getTmsaleProductFlg();

  /**
   * <code>int32 trade_dtls_cancle_fin_flg = 43;</code>
   */
  int getTradeDtlsCancleFinFlg();

  /**
   * <code>string trade_dtls_cancle_date = 44;</code>
   */
  java.lang.String getTradeDtlsCancleDate();
  /**
   * <code>string trade_dtls_cancle_date = 44;</code>
   */
  com.google.protobuf.ByteString
      getTradeDtlsCancleDateBytes();

  /**
   * <code>string shopping_day_disp_txt = 45;</code>
   */
  java.lang.String getShoppingDayDispTxt();
  /**
   * <code>string shopping_day_disp_txt = 45;</code>
   */
  com.google.protobuf.ByteString
      getShoppingDayDispTxtBytes();

  /**
   * <code>string shopping_timlmt_day = 46;</code>
   */
  java.lang.String getShoppingTimlmtDay();
  /**
   * <code>string shopping_timlmt_day = 46;</code>
   */
  com.google.protobuf.ByteString
      getShoppingTimlmtDayBytes();

  /**
   * <code>string div_timlmt_day = 47;</code>
   */
  java.lang.String getDivTimlmtDay();
  /**
   * <code>string div_timlmt_day = 47;</code>
   */
  com.google.protobuf.ByteString
      getDivTimlmtDayBytes();

  /**
   * <code>string digicon_ktn = 48;</code>
   */
  java.lang.String getDigiconKtn();
  /**
   * <code>string digicon_ktn = 48;</code>
   */
  com.google.protobuf.ByteString
      getDigiconKtnBytes();

  /**
   * <code>int32 adult_flg = 49;</code>
   */
  int getAdultFlg();

  /**
   * <code>int32 age_limit = 50;</code>
   */
  int getAgeLimit();

  /**
   * <code>int32 del_flg = 51;</code>
   */
  int getDelFlg();

  /**
   * <code>string create_date = 52;</code>
   */
  java.lang.String getCreateDate();
  /**
   * <code>string create_date = 52;</code>
   */
  com.google.protobuf.ByteString
      getCreateDateBytes();

  /**
   * <code>string update_date = 53;</code>
   */
  java.lang.String getUpdateDate();
  /**
   * <code>string update_date = 53;</code>
   */
  com.google.protobuf.ByteString
      getUpdateDateBytes();

  /**
   * <code>int64 create_id = 54;</code>
   */
  long getCreateId();

  /**
   * <code>int64 update_id = 55;</code>
   */
  long getUpdateId();

  /**
   * <code>string create_pgm_id = 56;</code>
   */
  java.lang.String getCreatePgmId();
  /**
   * <code>string create_pgm_id = 56;</code>
   */
  com.google.protobuf.ByteString
      getCreatePgmIdBytes();

  /**
   * <code>string update_pgm_id = 57;</code>
   */
  java.lang.String getUpdatePgmId();
  /**
   * <code>string update_pgm_id = 57;</code>
   */
  com.google.protobuf.ByteString
      getUpdatePgmIdBytes();

  /**
   * <code>int64 version = 58;</code>
   */
  long getVersion();
}
