// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tradedtls.proto

package grpc.trade.proto;

/**
 * Protobuf type {@code trade.ReplyTradeDetailList}
 */
public  final class ReplyTradeDetailList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trade.ReplyTradeDetailList)
    ReplyTradeDetailListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReplyTradeDetailList.newBuilder() to construct.
  private ReplyTradeDetailList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplyTradeDetailList() {
    tradeDetailList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReplyTradeDetailList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              tradeDetailList_ = new java.util.ArrayList<grpc.trade.proto.ReplyTradeDetail>();
              mutable_bitField0_ |= 0x00000001;
            }
            tradeDetailList_.add(
                input.readMessage(grpc.trade.proto.ReplyTradeDetail.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        tradeDetailList_ = java.util.Collections.unmodifiableList(tradeDetailList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.trade.proto.TradeDetailProto.internal_static_trade_ReplyTradeDetailList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.trade.proto.TradeDetailProto.internal_static_trade_ReplyTradeDetailList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.trade.proto.ReplyTradeDetailList.class, grpc.trade.proto.ReplyTradeDetailList.Builder.class);
  }

  public static final int TRADEDETAILLIST_FIELD_NUMBER = 1;
  private java.util.List<grpc.trade.proto.ReplyTradeDetail> tradeDetailList_;
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  public java.util.List<grpc.trade.proto.ReplyTradeDetail> getTradeDetailListList() {
    return tradeDetailList_;
  }
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  public java.util.List<? extends grpc.trade.proto.ReplyTradeDetailOrBuilder> 
      getTradeDetailListOrBuilderList() {
    return tradeDetailList_;
  }
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  public int getTradeDetailListCount() {
    return tradeDetailList_.size();
  }
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  public grpc.trade.proto.ReplyTradeDetail getTradeDetailList(int index) {
    return tradeDetailList_.get(index);
  }
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  public grpc.trade.proto.ReplyTradeDetailOrBuilder getTradeDetailListOrBuilder(
      int index) {
    return tradeDetailList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tradeDetailList_.size(); i++) {
      output.writeMessage(1, tradeDetailList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tradeDetailList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tradeDetailList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.trade.proto.ReplyTradeDetailList)) {
      return super.equals(obj);
    }
    grpc.trade.proto.ReplyTradeDetailList other = (grpc.trade.proto.ReplyTradeDetailList) obj;

    boolean result = true;
    result = result && getTradeDetailListList()
        .equals(other.getTradeDetailListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTradeDetailListCount() > 0) {
      hash = (37 * hash) + TRADEDETAILLIST_FIELD_NUMBER;
      hash = (53 * hash) + getTradeDetailListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.ReplyTradeDetailList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.trade.proto.ReplyTradeDetailList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trade.ReplyTradeDetailList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trade.ReplyTradeDetailList)
      grpc.trade.proto.ReplyTradeDetailListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.trade.proto.TradeDetailProto.internal_static_trade_ReplyTradeDetailList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.trade.proto.TradeDetailProto.internal_static_trade_ReplyTradeDetailList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.trade.proto.ReplyTradeDetailList.class, grpc.trade.proto.ReplyTradeDetailList.Builder.class);
    }

    // Construct using grpc.trade.proto.ReplyTradeDetailList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTradeDetailListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (tradeDetailListBuilder_ == null) {
        tradeDetailList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tradeDetailListBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.trade.proto.TradeDetailProto.internal_static_trade_ReplyTradeDetailList_descriptor;
    }

    public grpc.trade.proto.ReplyTradeDetailList getDefaultInstanceForType() {
      return grpc.trade.proto.ReplyTradeDetailList.getDefaultInstance();
    }

    public grpc.trade.proto.ReplyTradeDetailList build() {
      grpc.trade.proto.ReplyTradeDetailList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.trade.proto.ReplyTradeDetailList buildPartial() {
      grpc.trade.proto.ReplyTradeDetailList result = new grpc.trade.proto.ReplyTradeDetailList(this);
      int from_bitField0_ = bitField0_;
      if (tradeDetailListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          tradeDetailList_ = java.util.Collections.unmodifiableList(tradeDetailList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tradeDetailList_ = tradeDetailList_;
      } else {
        result.tradeDetailList_ = tradeDetailListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.trade.proto.ReplyTradeDetailList) {
        return mergeFrom((grpc.trade.proto.ReplyTradeDetailList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.trade.proto.ReplyTradeDetailList other) {
      if (other == grpc.trade.proto.ReplyTradeDetailList.getDefaultInstance()) return this;
      if (tradeDetailListBuilder_ == null) {
        if (!other.tradeDetailList_.isEmpty()) {
          if (tradeDetailList_.isEmpty()) {
            tradeDetailList_ = other.tradeDetailList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTradeDetailListIsMutable();
            tradeDetailList_.addAll(other.tradeDetailList_);
          }
          onChanged();
        }
      } else {
        if (!other.tradeDetailList_.isEmpty()) {
          if (tradeDetailListBuilder_.isEmpty()) {
            tradeDetailListBuilder_.dispose();
            tradeDetailListBuilder_ = null;
            tradeDetailList_ = other.tradeDetailList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tradeDetailListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTradeDetailListFieldBuilder() : null;
          } else {
            tradeDetailListBuilder_.addAllMessages(other.tradeDetailList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.trade.proto.ReplyTradeDetailList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.trade.proto.ReplyTradeDetailList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.trade.proto.ReplyTradeDetail> tradeDetailList_ =
      java.util.Collections.emptyList();
    private void ensureTradeDetailListIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        tradeDetailList_ = new java.util.ArrayList<grpc.trade.proto.ReplyTradeDetail>(tradeDetailList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.trade.proto.ReplyTradeDetail, grpc.trade.proto.ReplyTradeDetail.Builder, grpc.trade.proto.ReplyTradeDetailOrBuilder> tradeDetailListBuilder_;

    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public java.util.List<grpc.trade.proto.ReplyTradeDetail> getTradeDetailListList() {
      if (tradeDetailListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tradeDetailList_);
      } else {
        return tradeDetailListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public int getTradeDetailListCount() {
      if (tradeDetailListBuilder_ == null) {
        return tradeDetailList_.size();
      } else {
        return tradeDetailListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public grpc.trade.proto.ReplyTradeDetail getTradeDetailList(int index) {
      if (tradeDetailListBuilder_ == null) {
        return tradeDetailList_.get(index);
      } else {
        return tradeDetailListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder setTradeDetailList(
        int index, grpc.trade.proto.ReplyTradeDetail value) {
      if (tradeDetailListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradeDetailListIsMutable();
        tradeDetailList_.set(index, value);
        onChanged();
      } else {
        tradeDetailListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder setTradeDetailList(
        int index, grpc.trade.proto.ReplyTradeDetail.Builder builderForValue) {
      if (tradeDetailListBuilder_ == null) {
        ensureTradeDetailListIsMutable();
        tradeDetailList_.set(index, builderForValue.build());
        onChanged();
      } else {
        tradeDetailListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder addTradeDetailList(grpc.trade.proto.ReplyTradeDetail value) {
      if (tradeDetailListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradeDetailListIsMutable();
        tradeDetailList_.add(value);
        onChanged();
      } else {
        tradeDetailListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder addTradeDetailList(
        int index, grpc.trade.proto.ReplyTradeDetail value) {
      if (tradeDetailListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradeDetailListIsMutable();
        tradeDetailList_.add(index, value);
        onChanged();
      } else {
        tradeDetailListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder addTradeDetailList(
        grpc.trade.proto.ReplyTradeDetail.Builder builderForValue) {
      if (tradeDetailListBuilder_ == null) {
        ensureTradeDetailListIsMutable();
        tradeDetailList_.add(builderForValue.build());
        onChanged();
      } else {
        tradeDetailListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder addTradeDetailList(
        int index, grpc.trade.proto.ReplyTradeDetail.Builder builderForValue) {
      if (tradeDetailListBuilder_ == null) {
        ensureTradeDetailListIsMutable();
        tradeDetailList_.add(index, builderForValue.build());
        onChanged();
      } else {
        tradeDetailListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder addAllTradeDetailList(
        java.lang.Iterable<? extends grpc.trade.proto.ReplyTradeDetail> values) {
      if (tradeDetailListBuilder_ == null) {
        ensureTradeDetailListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tradeDetailList_);
        onChanged();
      } else {
        tradeDetailListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder clearTradeDetailList() {
      if (tradeDetailListBuilder_ == null) {
        tradeDetailList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tradeDetailListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public Builder removeTradeDetailList(int index) {
      if (tradeDetailListBuilder_ == null) {
        ensureTradeDetailListIsMutable();
        tradeDetailList_.remove(index);
        onChanged();
      } else {
        tradeDetailListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public grpc.trade.proto.ReplyTradeDetail.Builder getTradeDetailListBuilder(
        int index) {
      return getTradeDetailListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public grpc.trade.proto.ReplyTradeDetailOrBuilder getTradeDetailListOrBuilder(
        int index) {
      if (tradeDetailListBuilder_ == null) {
        return tradeDetailList_.get(index);  } else {
        return tradeDetailListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public java.util.List<? extends grpc.trade.proto.ReplyTradeDetailOrBuilder> 
         getTradeDetailListOrBuilderList() {
      if (tradeDetailListBuilder_ != null) {
        return tradeDetailListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tradeDetailList_);
      }
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public grpc.trade.proto.ReplyTradeDetail.Builder addTradeDetailListBuilder() {
      return getTradeDetailListFieldBuilder().addBuilder(
          grpc.trade.proto.ReplyTradeDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public grpc.trade.proto.ReplyTradeDetail.Builder addTradeDetailListBuilder(
        int index) {
      return getTradeDetailListFieldBuilder().addBuilder(
          index, grpc.trade.proto.ReplyTradeDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
     */
    public java.util.List<grpc.trade.proto.ReplyTradeDetail.Builder> 
         getTradeDetailListBuilderList() {
      return getTradeDetailListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.trade.proto.ReplyTradeDetail, grpc.trade.proto.ReplyTradeDetail.Builder, grpc.trade.proto.ReplyTradeDetailOrBuilder> 
        getTradeDetailListFieldBuilder() {
      if (tradeDetailListBuilder_ == null) {
        tradeDetailListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.trade.proto.ReplyTradeDetail, grpc.trade.proto.ReplyTradeDetail.Builder, grpc.trade.proto.ReplyTradeDetailOrBuilder>(
                tradeDetailList_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        tradeDetailList_ = null;
      }
      return tradeDetailListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trade.ReplyTradeDetailList)
  }

  // @@protoc_insertion_point(class_scope:trade.ReplyTradeDetailList)
  private static final grpc.trade.proto.ReplyTradeDetailList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.trade.proto.ReplyTradeDetailList();
  }

  public static grpc.trade.proto.ReplyTradeDetailList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplyTradeDetailList>
      PARSER = new com.google.protobuf.AbstractParser<ReplyTradeDetailList>() {
    public ReplyTradeDetailList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReplyTradeDetailList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplyTradeDetailList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplyTradeDetailList> getParserForType() {
    return PARSER;
  }

  public grpc.trade.proto.ReplyTradeDetailList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

