// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package grpc.trade.proto;

/**
 * Protobuf type {@code trade.ReplyTrade}
 */
public  final class ReplyTrade extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trade.ReplyTrade)
    ReplyTradeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReplyTrade.newBuilder() to construct.
  private ReplyTrade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplyTrade() {
    id_ = 0L;
    clid_ = 0L;
    tradeNo_ = 0L;
    destinationName_ = "";
    destinationNameKana_ = "";
    destinationZip_ = "";
    destinationAddress_ = "";
    destinationTel_ = "";
    destinationDaytimeConadr_ = "";
    destinationStoreCd_ = "";
    destinationNameEdit_ = "";
    destinationAddressEdit_ = "";
    destinationTelEdit_ = "";
    destinationZipEdit_ = "";
    destinationDaytimeConadrEdit_ = "";
    destinationNameKanaEdit_ = "";
    destinationStoreCdEdit_ = "";
    userCmt_ = "";
    buyDate_ = "";
    delFlg_ = 0;
    createDate_ = "";
    updateDate_ = "";
    createId_ = 0;
    updateId_ = 0;
    createPgmId_ = "";
    updatePgmId_ = "";
    version_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReplyTrade(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 16: {

            clid_ = input.readInt64();
            break;
          }
          case 24: {

            tradeNo_ = input.readInt64();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationName_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationNameKana_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationZip_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationAddress_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationTel_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationDaytimeConadr_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationStoreCd_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationNameEdit_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationAddressEdit_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationTelEdit_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationZipEdit_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationDaytimeConadrEdit_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationNameKanaEdit_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            destinationStoreCdEdit_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            userCmt_ = s;
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            buyDate_ = s;
            break;
          }
          case 160: {

            delFlg_ = input.readInt32();
            break;
          }
          case 170: {
            java.lang.String s = input.readStringRequireUtf8();

            createDate_ = s;
            break;
          }
          case 178: {
            java.lang.String s = input.readStringRequireUtf8();

            updateDate_ = s;
            break;
          }
          case 184: {

            createId_ = input.readInt32();
            break;
          }
          case 192: {

            updateId_ = input.readInt32();
            break;
          }
          case 202: {
            java.lang.String s = input.readStringRequireUtf8();

            createPgmId_ = s;
            break;
          }
          case 210: {
            java.lang.String s = input.readStringRequireUtf8();

            updatePgmId_ = s;
            break;
          }
          case 216: {

            version_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.trade.proto.TradeProto.internal_static_trade_ReplyTrade_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.trade.proto.TradeProto.internal_static_trade_ReplyTrade_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.trade.proto.ReplyTrade.class, grpc.trade.proto.ReplyTrade.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int CLID_FIELD_NUMBER = 2;
  private long clid_;
  /**
   * <code>int64 clid = 2;</code>
   */
  public long getClid() {
    return clid_;
  }

  public static final int TRADE_NO_FIELD_NUMBER = 3;
  private long tradeNo_;
  /**
   * <code>int64 trade_no = 3;</code>
   */
  public long getTradeNo() {
    return tradeNo_;
  }

  public static final int DESTINATION_NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object destinationName_;
  /**
   * <code>string destination_name = 4;</code>
   */
  public java.lang.String getDestinationName() {
    java.lang.Object ref = destinationName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationName_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationNameBytes() {
    java.lang.Object ref = destinationName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_NAME_KANA_FIELD_NUMBER = 5;
  private volatile java.lang.Object destinationNameKana_;
  /**
   * <code>string destination_name_kana = 5;</code>
   */
  public java.lang.String getDestinationNameKana() {
    java.lang.Object ref = destinationNameKana_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationNameKana_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_name_kana = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationNameKanaBytes() {
    java.lang.Object ref = destinationNameKana_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationNameKana_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_ZIP_FIELD_NUMBER = 6;
  private volatile java.lang.Object destinationZip_;
  /**
   * <code>string destination_zip = 6;</code>
   */
  public java.lang.String getDestinationZip() {
    java.lang.Object ref = destinationZip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationZip_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_zip = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationZipBytes() {
    java.lang.Object ref = destinationZip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationZip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_ADDRESS_FIELD_NUMBER = 7;
  private volatile java.lang.Object destinationAddress_;
  /**
   * <code>string destination_address = 7;</code>
   */
  public java.lang.String getDestinationAddress() {
    java.lang.Object ref = destinationAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_address = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationAddressBytes() {
    java.lang.Object ref = destinationAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_TEL_FIELD_NUMBER = 8;
  private volatile java.lang.Object destinationTel_;
  /**
   * <code>string destination_tel = 8;</code>
   */
  public java.lang.String getDestinationTel() {
    java.lang.Object ref = destinationTel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationTel_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_tel = 8;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationTelBytes() {
    java.lang.Object ref = destinationTel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationTel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_DAYTIME_CONADR_FIELD_NUMBER = 9;
  private volatile java.lang.Object destinationDaytimeConadr_;
  /**
   * <code>string destination_daytime_conadr = 9;</code>
   */
  public java.lang.String getDestinationDaytimeConadr() {
    java.lang.Object ref = destinationDaytimeConadr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationDaytimeConadr_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_daytime_conadr = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationDaytimeConadrBytes() {
    java.lang.Object ref = destinationDaytimeConadr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationDaytimeConadr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_STORE_CD_FIELD_NUMBER = 10;
  private volatile java.lang.Object destinationStoreCd_;
  /**
   * <code>string destination_store_cd = 10;</code>
   */
  public java.lang.String getDestinationStoreCd() {
    java.lang.Object ref = destinationStoreCd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationStoreCd_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_store_cd = 10;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationStoreCdBytes() {
    java.lang.Object ref = destinationStoreCd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationStoreCd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_NAME_EDIT_FIELD_NUMBER = 11;
  private volatile java.lang.Object destinationNameEdit_;
  /**
   * <code>string destination_name_edit = 11;</code>
   */
  public java.lang.String getDestinationNameEdit() {
    java.lang.Object ref = destinationNameEdit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationNameEdit_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_name_edit = 11;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationNameEditBytes() {
    java.lang.Object ref = destinationNameEdit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationNameEdit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_ADDRESS_EDIT_FIELD_NUMBER = 12;
  private volatile java.lang.Object destinationAddressEdit_;
  /**
   * <code>string destination_address_edit = 12;</code>
   */
  public java.lang.String getDestinationAddressEdit() {
    java.lang.Object ref = destinationAddressEdit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationAddressEdit_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_address_edit = 12;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationAddressEditBytes() {
    java.lang.Object ref = destinationAddressEdit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationAddressEdit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_TEL_EDIT_FIELD_NUMBER = 13;
  private volatile java.lang.Object destinationTelEdit_;
  /**
   * <code>string destination_tel_edit = 13;</code>
   */
  public java.lang.String getDestinationTelEdit() {
    java.lang.Object ref = destinationTelEdit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationTelEdit_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_tel_edit = 13;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationTelEditBytes() {
    java.lang.Object ref = destinationTelEdit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationTelEdit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_ZIP_EDIT_FIELD_NUMBER = 14;
  private volatile java.lang.Object destinationZipEdit_;
  /**
   * <code>string destination_zip_edit = 14;</code>
   */
  public java.lang.String getDestinationZipEdit() {
    java.lang.Object ref = destinationZipEdit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationZipEdit_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_zip_edit = 14;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationZipEditBytes() {
    java.lang.Object ref = destinationZipEdit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationZipEdit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_DAYTIME_CONADR_EDIT_FIELD_NUMBER = 15;
  private volatile java.lang.Object destinationDaytimeConadrEdit_;
  /**
   * <code>string destination_daytime_conadr_edit = 15;</code>
   */
  public java.lang.String getDestinationDaytimeConadrEdit() {
    java.lang.Object ref = destinationDaytimeConadrEdit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationDaytimeConadrEdit_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_daytime_conadr_edit = 15;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationDaytimeConadrEditBytes() {
    java.lang.Object ref = destinationDaytimeConadrEdit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationDaytimeConadrEdit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_NAME_KANA_EDIT_FIELD_NUMBER = 16;
  private volatile java.lang.Object destinationNameKanaEdit_;
  /**
   * <code>string destination_name_kana_edit = 16;</code>
   */
  public java.lang.String getDestinationNameKanaEdit() {
    java.lang.Object ref = destinationNameKanaEdit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationNameKanaEdit_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_name_kana_edit = 16;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationNameKanaEditBytes() {
    java.lang.Object ref = destinationNameKanaEdit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationNameKanaEdit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_STORE_CD_EDIT_FIELD_NUMBER = 17;
  private volatile java.lang.Object destinationStoreCdEdit_;
  /**
   * <code>string destination_store_cd_edit = 17;</code>
   */
  public java.lang.String getDestinationStoreCdEdit() {
    java.lang.Object ref = destinationStoreCdEdit_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinationStoreCdEdit_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_store_cd_edit = 17;</code>
   */
  public com.google.protobuf.ByteString
      getDestinationStoreCdEditBytes() {
    java.lang.Object ref = destinationStoreCdEdit_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destinationStoreCdEdit_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_CMT_FIELD_NUMBER = 18;
  private volatile java.lang.Object userCmt_;
  /**
   * <code>string user_cmt = 18;</code>
   */
  public java.lang.String getUserCmt() {
    java.lang.Object ref = userCmt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userCmt_ = s;
      return s;
    }
  }
  /**
   * <code>string user_cmt = 18;</code>
   */
  public com.google.protobuf.ByteString
      getUserCmtBytes() {
    java.lang.Object ref = userCmt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userCmt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUY_DATE_FIELD_NUMBER = 19;
  private volatile java.lang.Object buyDate_;
  /**
   * <code>string buy_date = 19;</code>
   */
  public java.lang.String getBuyDate() {
    java.lang.Object ref = buyDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      buyDate_ = s;
      return s;
    }
  }
  /**
   * <code>string buy_date = 19;</code>
   */
  public com.google.protobuf.ByteString
      getBuyDateBytes() {
    java.lang.Object ref = buyDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buyDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEL_FLG_FIELD_NUMBER = 20;
  private int delFlg_;
  /**
   * <code>int32 del_flg = 20;</code>
   */
  public int getDelFlg() {
    return delFlg_;
  }

  public static final int CREATE_DATE_FIELD_NUMBER = 21;
  private volatile java.lang.Object createDate_;
  /**
   * <code>string create_date = 21;</code>
   */
  public java.lang.String getCreateDate() {
    java.lang.Object ref = createDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createDate_ = s;
      return s;
    }
  }
  /**
   * <code>string create_date = 21;</code>
   */
  public com.google.protobuf.ByteString
      getCreateDateBytes() {
    java.lang.Object ref = createDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_DATE_FIELD_NUMBER = 22;
  private volatile java.lang.Object updateDate_;
  /**
   * <code>string update_date = 22;</code>
   */
  public java.lang.String getUpdateDate() {
    java.lang.Object ref = updateDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updateDate_ = s;
      return s;
    }
  }
  /**
   * <code>string update_date = 22;</code>
   */
  public com.google.protobuf.ByteString
      getUpdateDateBytes() {
    java.lang.Object ref = updateDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updateDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATE_ID_FIELD_NUMBER = 23;
  private int createId_;
  /**
   * <code>int32 create_id = 23;</code>
   */
  public int getCreateId() {
    return createId_;
  }

  public static final int UPDATE_ID_FIELD_NUMBER = 24;
  private int updateId_;
  /**
   * <code>int32 update_id = 24;</code>
   */
  public int getUpdateId() {
    return updateId_;
  }

  public static final int CREATE_PGM_ID_FIELD_NUMBER = 25;
  private volatile java.lang.Object createPgmId_;
  /**
   * <code>string create_pgm_id = 25;</code>
   */
  public java.lang.String getCreatePgmId() {
    java.lang.Object ref = createPgmId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createPgmId_ = s;
      return s;
    }
  }
  /**
   * <code>string create_pgm_id = 25;</code>
   */
  public com.google.protobuf.ByteString
      getCreatePgmIdBytes() {
    java.lang.Object ref = createPgmId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createPgmId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_PGM_ID_FIELD_NUMBER = 26;
  private volatile java.lang.Object updatePgmId_;
  /**
   * <code>string update_pgm_id = 26;</code>
   */
  public java.lang.String getUpdatePgmId() {
    java.lang.Object ref = updatePgmId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updatePgmId_ = s;
      return s;
    }
  }
  /**
   * <code>string update_pgm_id = 26;</code>
   */
  public com.google.protobuf.ByteString
      getUpdatePgmIdBytes() {
    java.lang.Object ref = updatePgmId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updatePgmId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 27;
  private long version_;
  /**
   * <code>int64 version = 27;</code>
   */
  public long getVersion() {
    return version_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (clid_ != 0L) {
      output.writeInt64(2, clid_);
    }
    if (tradeNo_ != 0L) {
      output.writeInt64(3, tradeNo_);
    }
    if (!getDestinationNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destinationName_);
    }
    if (!getDestinationNameKanaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, destinationNameKana_);
    }
    if (!getDestinationZipBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, destinationZip_);
    }
    if (!getDestinationAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, destinationAddress_);
    }
    if (!getDestinationTelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, destinationTel_);
    }
    if (!getDestinationDaytimeConadrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, destinationDaytimeConadr_);
    }
    if (!getDestinationStoreCdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, destinationStoreCd_);
    }
    if (!getDestinationNameEditBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, destinationNameEdit_);
    }
    if (!getDestinationAddressEditBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, destinationAddressEdit_);
    }
    if (!getDestinationTelEditBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, destinationTelEdit_);
    }
    if (!getDestinationZipEditBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, destinationZipEdit_);
    }
    if (!getDestinationDaytimeConadrEditBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, destinationDaytimeConadrEdit_);
    }
    if (!getDestinationNameKanaEditBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, destinationNameKanaEdit_);
    }
    if (!getDestinationStoreCdEditBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, destinationStoreCdEdit_);
    }
    if (!getUserCmtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, userCmt_);
    }
    if (!getBuyDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, buyDate_);
    }
    if (delFlg_ != 0) {
      output.writeInt32(20, delFlg_);
    }
    if (!getCreateDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 21, createDate_);
    }
    if (!getUpdateDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 22, updateDate_);
    }
    if (createId_ != 0) {
      output.writeInt32(23, createId_);
    }
    if (updateId_ != 0) {
      output.writeInt32(24, updateId_);
    }
    if (!getCreatePgmIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 25, createPgmId_);
    }
    if (!getUpdatePgmIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 26, updatePgmId_);
    }
    if (version_ != 0L) {
      output.writeInt64(27, version_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (clid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, clid_);
    }
    if (tradeNo_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, tradeNo_);
    }
    if (!getDestinationNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destinationName_);
    }
    if (!getDestinationNameKanaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, destinationNameKana_);
    }
    if (!getDestinationZipBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, destinationZip_);
    }
    if (!getDestinationAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, destinationAddress_);
    }
    if (!getDestinationTelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, destinationTel_);
    }
    if (!getDestinationDaytimeConadrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, destinationDaytimeConadr_);
    }
    if (!getDestinationStoreCdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, destinationStoreCd_);
    }
    if (!getDestinationNameEditBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, destinationNameEdit_);
    }
    if (!getDestinationAddressEditBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, destinationAddressEdit_);
    }
    if (!getDestinationTelEditBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, destinationTelEdit_);
    }
    if (!getDestinationZipEditBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, destinationZipEdit_);
    }
    if (!getDestinationDaytimeConadrEditBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, destinationDaytimeConadrEdit_);
    }
    if (!getDestinationNameKanaEditBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, destinationNameKanaEdit_);
    }
    if (!getDestinationStoreCdEditBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, destinationStoreCdEdit_);
    }
    if (!getUserCmtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, userCmt_);
    }
    if (!getBuyDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, buyDate_);
    }
    if (delFlg_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(20, delFlg_);
    }
    if (!getCreateDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(21, createDate_);
    }
    if (!getUpdateDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(22, updateDate_);
    }
    if (createId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, createId_);
    }
    if (updateId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(24, updateId_);
    }
    if (!getCreatePgmIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(25, createPgmId_);
    }
    if (!getUpdatePgmIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(26, updatePgmId_);
    }
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(27, version_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.trade.proto.ReplyTrade)) {
      return super.equals(obj);
    }
    grpc.trade.proto.ReplyTrade other = (grpc.trade.proto.ReplyTrade) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && (getClid()
        == other.getClid());
    result = result && (getTradeNo()
        == other.getTradeNo());
    result = result && getDestinationName()
        .equals(other.getDestinationName());
    result = result && getDestinationNameKana()
        .equals(other.getDestinationNameKana());
    result = result && getDestinationZip()
        .equals(other.getDestinationZip());
    result = result && getDestinationAddress()
        .equals(other.getDestinationAddress());
    result = result && getDestinationTel()
        .equals(other.getDestinationTel());
    result = result && getDestinationDaytimeConadr()
        .equals(other.getDestinationDaytimeConadr());
    result = result && getDestinationStoreCd()
        .equals(other.getDestinationStoreCd());
    result = result && getDestinationNameEdit()
        .equals(other.getDestinationNameEdit());
    result = result && getDestinationAddressEdit()
        .equals(other.getDestinationAddressEdit());
    result = result && getDestinationTelEdit()
        .equals(other.getDestinationTelEdit());
    result = result && getDestinationZipEdit()
        .equals(other.getDestinationZipEdit());
    result = result && getDestinationDaytimeConadrEdit()
        .equals(other.getDestinationDaytimeConadrEdit());
    result = result && getDestinationNameKanaEdit()
        .equals(other.getDestinationNameKanaEdit());
    result = result && getDestinationStoreCdEdit()
        .equals(other.getDestinationStoreCdEdit());
    result = result && getUserCmt()
        .equals(other.getUserCmt());
    result = result && getBuyDate()
        .equals(other.getBuyDate());
    result = result && (getDelFlg()
        == other.getDelFlg());
    result = result && getCreateDate()
        .equals(other.getCreateDate());
    result = result && getUpdateDate()
        .equals(other.getUpdateDate());
    result = result && (getCreateId()
        == other.getCreateId());
    result = result && (getUpdateId()
        == other.getUpdateId());
    result = result && getCreatePgmId()
        .equals(other.getCreatePgmId());
    result = result && getUpdatePgmId()
        .equals(other.getUpdatePgmId());
    result = result && (getVersion()
        == other.getVersion());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + CLID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClid());
    hash = (37 * hash) + TRADE_NO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTradeNo());
    hash = (37 * hash) + DESTINATION_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationName().hashCode();
    hash = (37 * hash) + DESTINATION_NAME_KANA_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationNameKana().hashCode();
    hash = (37 * hash) + DESTINATION_ZIP_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationZip().hashCode();
    hash = (37 * hash) + DESTINATION_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationAddress().hashCode();
    hash = (37 * hash) + DESTINATION_TEL_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationTel().hashCode();
    hash = (37 * hash) + DESTINATION_DAYTIME_CONADR_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationDaytimeConadr().hashCode();
    hash = (37 * hash) + DESTINATION_STORE_CD_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationStoreCd().hashCode();
    hash = (37 * hash) + DESTINATION_NAME_EDIT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationNameEdit().hashCode();
    hash = (37 * hash) + DESTINATION_ADDRESS_EDIT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationAddressEdit().hashCode();
    hash = (37 * hash) + DESTINATION_TEL_EDIT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationTelEdit().hashCode();
    hash = (37 * hash) + DESTINATION_ZIP_EDIT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationZipEdit().hashCode();
    hash = (37 * hash) + DESTINATION_DAYTIME_CONADR_EDIT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationDaytimeConadrEdit().hashCode();
    hash = (37 * hash) + DESTINATION_NAME_KANA_EDIT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationNameKanaEdit().hashCode();
    hash = (37 * hash) + DESTINATION_STORE_CD_EDIT_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationStoreCdEdit().hashCode();
    hash = (37 * hash) + USER_CMT_FIELD_NUMBER;
    hash = (53 * hash) + getUserCmt().hashCode();
    hash = (37 * hash) + BUY_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getBuyDate().hashCode();
    hash = (37 * hash) + DEL_FLG_FIELD_NUMBER;
    hash = (53 * hash) + getDelFlg();
    hash = (37 * hash) + CREATE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getCreateDate().hashCode();
    hash = (37 * hash) + UPDATE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateDate().hashCode();
    hash = (37 * hash) + CREATE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCreateId();
    hash = (37 * hash) + UPDATE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateId();
    hash = (37 * hash) + CREATE_PGM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCreatePgmId().hashCode();
    hash = (37 * hash) + UPDATE_PGM_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatePgmId().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.trade.proto.ReplyTrade parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTrade parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.ReplyTrade parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.ReplyTrade parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.trade.proto.ReplyTrade prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trade.ReplyTrade}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trade.ReplyTrade)
      grpc.trade.proto.ReplyTradeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.trade.proto.TradeProto.internal_static_trade_ReplyTrade_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.trade.proto.TradeProto.internal_static_trade_ReplyTrade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.trade.proto.ReplyTrade.class, grpc.trade.proto.ReplyTrade.Builder.class);
    }

    // Construct using grpc.trade.proto.ReplyTrade.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      clid_ = 0L;

      tradeNo_ = 0L;

      destinationName_ = "";

      destinationNameKana_ = "";

      destinationZip_ = "";

      destinationAddress_ = "";

      destinationTel_ = "";

      destinationDaytimeConadr_ = "";

      destinationStoreCd_ = "";

      destinationNameEdit_ = "";

      destinationAddressEdit_ = "";

      destinationTelEdit_ = "";

      destinationZipEdit_ = "";

      destinationDaytimeConadrEdit_ = "";

      destinationNameKanaEdit_ = "";

      destinationStoreCdEdit_ = "";

      userCmt_ = "";

      buyDate_ = "";

      delFlg_ = 0;

      createDate_ = "";

      updateDate_ = "";

      createId_ = 0;

      updateId_ = 0;

      createPgmId_ = "";

      updatePgmId_ = "";

      version_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.trade.proto.TradeProto.internal_static_trade_ReplyTrade_descriptor;
    }

    public grpc.trade.proto.ReplyTrade getDefaultInstanceForType() {
      return grpc.trade.proto.ReplyTrade.getDefaultInstance();
    }

    public grpc.trade.proto.ReplyTrade build() {
      grpc.trade.proto.ReplyTrade result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.trade.proto.ReplyTrade buildPartial() {
      grpc.trade.proto.ReplyTrade result = new grpc.trade.proto.ReplyTrade(this);
      result.id_ = id_;
      result.clid_ = clid_;
      result.tradeNo_ = tradeNo_;
      result.destinationName_ = destinationName_;
      result.destinationNameKana_ = destinationNameKana_;
      result.destinationZip_ = destinationZip_;
      result.destinationAddress_ = destinationAddress_;
      result.destinationTel_ = destinationTel_;
      result.destinationDaytimeConadr_ = destinationDaytimeConadr_;
      result.destinationStoreCd_ = destinationStoreCd_;
      result.destinationNameEdit_ = destinationNameEdit_;
      result.destinationAddressEdit_ = destinationAddressEdit_;
      result.destinationTelEdit_ = destinationTelEdit_;
      result.destinationZipEdit_ = destinationZipEdit_;
      result.destinationDaytimeConadrEdit_ = destinationDaytimeConadrEdit_;
      result.destinationNameKanaEdit_ = destinationNameKanaEdit_;
      result.destinationStoreCdEdit_ = destinationStoreCdEdit_;
      result.userCmt_ = userCmt_;
      result.buyDate_ = buyDate_;
      result.delFlg_ = delFlg_;
      result.createDate_ = createDate_;
      result.updateDate_ = updateDate_;
      result.createId_ = createId_;
      result.updateId_ = updateId_;
      result.createPgmId_ = createPgmId_;
      result.updatePgmId_ = updatePgmId_;
      result.version_ = version_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.trade.proto.ReplyTrade) {
        return mergeFrom((grpc.trade.proto.ReplyTrade)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.trade.proto.ReplyTrade other) {
      if (other == grpc.trade.proto.ReplyTrade.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getClid() != 0L) {
        setClid(other.getClid());
      }
      if (other.getTradeNo() != 0L) {
        setTradeNo(other.getTradeNo());
      }
      if (!other.getDestinationName().isEmpty()) {
        destinationName_ = other.destinationName_;
        onChanged();
      }
      if (!other.getDestinationNameKana().isEmpty()) {
        destinationNameKana_ = other.destinationNameKana_;
        onChanged();
      }
      if (!other.getDestinationZip().isEmpty()) {
        destinationZip_ = other.destinationZip_;
        onChanged();
      }
      if (!other.getDestinationAddress().isEmpty()) {
        destinationAddress_ = other.destinationAddress_;
        onChanged();
      }
      if (!other.getDestinationTel().isEmpty()) {
        destinationTel_ = other.destinationTel_;
        onChanged();
      }
      if (!other.getDestinationDaytimeConadr().isEmpty()) {
        destinationDaytimeConadr_ = other.destinationDaytimeConadr_;
        onChanged();
      }
      if (!other.getDestinationStoreCd().isEmpty()) {
        destinationStoreCd_ = other.destinationStoreCd_;
        onChanged();
      }
      if (!other.getDestinationNameEdit().isEmpty()) {
        destinationNameEdit_ = other.destinationNameEdit_;
        onChanged();
      }
      if (!other.getDestinationAddressEdit().isEmpty()) {
        destinationAddressEdit_ = other.destinationAddressEdit_;
        onChanged();
      }
      if (!other.getDestinationTelEdit().isEmpty()) {
        destinationTelEdit_ = other.destinationTelEdit_;
        onChanged();
      }
      if (!other.getDestinationZipEdit().isEmpty()) {
        destinationZipEdit_ = other.destinationZipEdit_;
        onChanged();
      }
      if (!other.getDestinationDaytimeConadrEdit().isEmpty()) {
        destinationDaytimeConadrEdit_ = other.destinationDaytimeConadrEdit_;
        onChanged();
      }
      if (!other.getDestinationNameKanaEdit().isEmpty()) {
        destinationNameKanaEdit_ = other.destinationNameKanaEdit_;
        onChanged();
      }
      if (!other.getDestinationStoreCdEdit().isEmpty()) {
        destinationStoreCdEdit_ = other.destinationStoreCdEdit_;
        onChanged();
      }
      if (!other.getUserCmt().isEmpty()) {
        userCmt_ = other.userCmt_;
        onChanged();
      }
      if (!other.getBuyDate().isEmpty()) {
        buyDate_ = other.buyDate_;
        onChanged();
      }
      if (other.getDelFlg() != 0) {
        setDelFlg(other.getDelFlg());
      }
      if (!other.getCreateDate().isEmpty()) {
        createDate_ = other.createDate_;
        onChanged();
      }
      if (!other.getUpdateDate().isEmpty()) {
        updateDate_ = other.updateDate_;
        onChanged();
      }
      if (other.getCreateId() != 0) {
        setCreateId(other.getCreateId());
      }
      if (other.getUpdateId() != 0) {
        setUpdateId(other.getUpdateId());
      }
      if (!other.getCreatePgmId().isEmpty()) {
        createPgmId_ = other.createPgmId_;
        onChanged();
      }
      if (!other.getUpdatePgmId().isEmpty()) {
        updatePgmId_ = other.updatePgmId_;
        onChanged();
      }
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.trade.proto.ReplyTrade parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.trade.proto.ReplyTrade) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long clid_ ;
    /**
     * <code>int64 clid = 2;</code>
     */
    public long getClid() {
      return clid_;
    }
    /**
     * <code>int64 clid = 2;</code>
     */
    public Builder setClid(long value) {
      
      clid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 clid = 2;</code>
     */
    public Builder clearClid() {
      
      clid_ = 0L;
      onChanged();
      return this;
    }

    private long tradeNo_ ;
    /**
     * <code>int64 trade_no = 3;</code>
     */
    public long getTradeNo() {
      return tradeNo_;
    }
    /**
     * <code>int64 trade_no = 3;</code>
     */
    public Builder setTradeNo(long value) {
      
      tradeNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 trade_no = 3;</code>
     */
    public Builder clearTradeNo() {
      
      tradeNo_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object destinationName_ = "";
    /**
     * <code>string destination_name = 4;</code>
     */
    public java.lang.String getDestinationName() {
      java.lang.Object ref = destinationName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationNameBytes() {
      java.lang.Object ref = destinationName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_name = 4;</code>
     */
    public Builder setDestinationName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name = 4;</code>
     */
    public Builder clearDestinationName() {
      
      destinationName_ = getDefaultInstance().getDestinationName();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name = 4;</code>
     */
    public Builder setDestinationNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationNameKana_ = "";
    /**
     * <code>string destination_name_kana = 5;</code>
     */
    public java.lang.String getDestinationNameKana() {
      java.lang.Object ref = destinationNameKana_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationNameKana_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_name_kana = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationNameKanaBytes() {
      java.lang.Object ref = destinationNameKana_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationNameKana_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_name_kana = 5;</code>
     */
    public Builder setDestinationNameKana(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationNameKana_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name_kana = 5;</code>
     */
    public Builder clearDestinationNameKana() {
      
      destinationNameKana_ = getDefaultInstance().getDestinationNameKana();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name_kana = 5;</code>
     */
    public Builder setDestinationNameKanaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationNameKana_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationZip_ = "";
    /**
     * <code>string destination_zip = 6;</code>
     */
    public java.lang.String getDestinationZip() {
      java.lang.Object ref = destinationZip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationZip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_zip = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationZipBytes() {
      java.lang.Object ref = destinationZip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationZip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_zip = 6;</code>
     */
    public Builder setDestinationZip(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationZip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_zip = 6;</code>
     */
    public Builder clearDestinationZip() {
      
      destinationZip_ = getDefaultInstance().getDestinationZip();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_zip = 6;</code>
     */
    public Builder setDestinationZipBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationZip_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationAddress_ = "";
    /**
     * <code>string destination_address = 7;</code>
     */
    public java.lang.String getDestinationAddress() {
      java.lang.Object ref = destinationAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationAddressBytes() {
      java.lang.Object ref = destinationAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public Builder setDestinationAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public Builder clearDestinationAddress() {
      
      destinationAddress_ = getDefaultInstance().getDestinationAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_address = 7;</code>
     */
    public Builder setDestinationAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationTel_ = "";
    /**
     * <code>string destination_tel = 8;</code>
     */
    public java.lang.String getDestinationTel() {
      java.lang.Object ref = destinationTel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationTel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_tel = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationTelBytes() {
      java.lang.Object ref = destinationTel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationTel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_tel = 8;</code>
     */
    public Builder setDestinationTel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationTel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_tel = 8;</code>
     */
    public Builder clearDestinationTel() {
      
      destinationTel_ = getDefaultInstance().getDestinationTel();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_tel = 8;</code>
     */
    public Builder setDestinationTelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationTel_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationDaytimeConadr_ = "";
    /**
     * <code>string destination_daytime_conadr = 9;</code>
     */
    public java.lang.String getDestinationDaytimeConadr() {
      java.lang.Object ref = destinationDaytimeConadr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationDaytimeConadr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_daytime_conadr = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationDaytimeConadrBytes() {
      java.lang.Object ref = destinationDaytimeConadr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationDaytimeConadr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_daytime_conadr = 9;</code>
     */
    public Builder setDestinationDaytimeConadr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationDaytimeConadr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_daytime_conadr = 9;</code>
     */
    public Builder clearDestinationDaytimeConadr() {
      
      destinationDaytimeConadr_ = getDefaultInstance().getDestinationDaytimeConadr();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_daytime_conadr = 9;</code>
     */
    public Builder setDestinationDaytimeConadrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationDaytimeConadr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationStoreCd_ = "";
    /**
     * <code>string destination_store_cd = 10;</code>
     */
    public java.lang.String getDestinationStoreCd() {
      java.lang.Object ref = destinationStoreCd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationStoreCd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_store_cd = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationStoreCdBytes() {
      java.lang.Object ref = destinationStoreCd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationStoreCd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_store_cd = 10;</code>
     */
    public Builder setDestinationStoreCd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationStoreCd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_store_cd = 10;</code>
     */
    public Builder clearDestinationStoreCd() {
      
      destinationStoreCd_ = getDefaultInstance().getDestinationStoreCd();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_store_cd = 10;</code>
     */
    public Builder setDestinationStoreCdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationStoreCd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationNameEdit_ = "";
    /**
     * <code>string destination_name_edit = 11;</code>
     */
    public java.lang.String getDestinationNameEdit() {
      java.lang.Object ref = destinationNameEdit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationNameEdit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_name_edit = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationNameEditBytes() {
      java.lang.Object ref = destinationNameEdit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationNameEdit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_name_edit = 11;</code>
     */
    public Builder setDestinationNameEdit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationNameEdit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name_edit = 11;</code>
     */
    public Builder clearDestinationNameEdit() {
      
      destinationNameEdit_ = getDefaultInstance().getDestinationNameEdit();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name_edit = 11;</code>
     */
    public Builder setDestinationNameEditBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationNameEdit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationAddressEdit_ = "";
    /**
     * <code>string destination_address_edit = 12;</code>
     */
    public java.lang.String getDestinationAddressEdit() {
      java.lang.Object ref = destinationAddressEdit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationAddressEdit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_address_edit = 12;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationAddressEditBytes() {
      java.lang.Object ref = destinationAddressEdit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationAddressEdit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_address_edit = 12;</code>
     */
    public Builder setDestinationAddressEdit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationAddressEdit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_address_edit = 12;</code>
     */
    public Builder clearDestinationAddressEdit() {
      
      destinationAddressEdit_ = getDefaultInstance().getDestinationAddressEdit();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_address_edit = 12;</code>
     */
    public Builder setDestinationAddressEditBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationAddressEdit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationTelEdit_ = "";
    /**
     * <code>string destination_tel_edit = 13;</code>
     */
    public java.lang.String getDestinationTelEdit() {
      java.lang.Object ref = destinationTelEdit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationTelEdit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_tel_edit = 13;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationTelEditBytes() {
      java.lang.Object ref = destinationTelEdit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationTelEdit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_tel_edit = 13;</code>
     */
    public Builder setDestinationTelEdit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationTelEdit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_tel_edit = 13;</code>
     */
    public Builder clearDestinationTelEdit() {
      
      destinationTelEdit_ = getDefaultInstance().getDestinationTelEdit();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_tel_edit = 13;</code>
     */
    public Builder setDestinationTelEditBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationTelEdit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationZipEdit_ = "";
    /**
     * <code>string destination_zip_edit = 14;</code>
     */
    public java.lang.String getDestinationZipEdit() {
      java.lang.Object ref = destinationZipEdit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationZipEdit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_zip_edit = 14;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationZipEditBytes() {
      java.lang.Object ref = destinationZipEdit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationZipEdit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_zip_edit = 14;</code>
     */
    public Builder setDestinationZipEdit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationZipEdit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_zip_edit = 14;</code>
     */
    public Builder clearDestinationZipEdit() {
      
      destinationZipEdit_ = getDefaultInstance().getDestinationZipEdit();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_zip_edit = 14;</code>
     */
    public Builder setDestinationZipEditBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationZipEdit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationDaytimeConadrEdit_ = "";
    /**
     * <code>string destination_daytime_conadr_edit = 15;</code>
     */
    public java.lang.String getDestinationDaytimeConadrEdit() {
      java.lang.Object ref = destinationDaytimeConadrEdit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationDaytimeConadrEdit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_daytime_conadr_edit = 15;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationDaytimeConadrEditBytes() {
      java.lang.Object ref = destinationDaytimeConadrEdit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationDaytimeConadrEdit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_daytime_conadr_edit = 15;</code>
     */
    public Builder setDestinationDaytimeConadrEdit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationDaytimeConadrEdit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_daytime_conadr_edit = 15;</code>
     */
    public Builder clearDestinationDaytimeConadrEdit() {
      
      destinationDaytimeConadrEdit_ = getDefaultInstance().getDestinationDaytimeConadrEdit();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_daytime_conadr_edit = 15;</code>
     */
    public Builder setDestinationDaytimeConadrEditBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationDaytimeConadrEdit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationNameKanaEdit_ = "";
    /**
     * <code>string destination_name_kana_edit = 16;</code>
     */
    public java.lang.String getDestinationNameKanaEdit() {
      java.lang.Object ref = destinationNameKanaEdit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationNameKanaEdit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_name_kana_edit = 16;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationNameKanaEditBytes() {
      java.lang.Object ref = destinationNameKanaEdit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationNameKanaEdit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_name_kana_edit = 16;</code>
     */
    public Builder setDestinationNameKanaEdit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationNameKanaEdit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name_kana_edit = 16;</code>
     */
    public Builder clearDestinationNameKanaEdit() {
      
      destinationNameKanaEdit_ = getDefaultInstance().getDestinationNameKanaEdit();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_name_kana_edit = 16;</code>
     */
    public Builder setDestinationNameKanaEditBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationNameKanaEdit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object destinationStoreCdEdit_ = "";
    /**
     * <code>string destination_store_cd_edit = 17;</code>
     */
    public java.lang.String getDestinationStoreCdEdit() {
      java.lang.Object ref = destinationStoreCdEdit_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinationStoreCdEdit_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destination_store_cd_edit = 17;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationStoreCdEditBytes() {
      java.lang.Object ref = destinationStoreCdEdit_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destinationStoreCdEdit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_store_cd_edit = 17;</code>
     */
    public Builder setDestinationStoreCdEdit(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destinationStoreCdEdit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_store_cd_edit = 17;</code>
     */
    public Builder clearDestinationStoreCdEdit() {
      
      destinationStoreCdEdit_ = getDefaultInstance().getDestinationStoreCdEdit();
      onChanged();
      return this;
    }
    /**
     * <code>string destination_store_cd_edit = 17;</code>
     */
    public Builder setDestinationStoreCdEditBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destinationStoreCdEdit_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userCmt_ = "";
    /**
     * <code>string user_cmt = 18;</code>
     */
    public java.lang.String getUserCmt() {
      java.lang.Object ref = userCmt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userCmt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_cmt = 18;</code>
     */
    public com.google.protobuf.ByteString
        getUserCmtBytes() {
      java.lang.Object ref = userCmt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userCmt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_cmt = 18;</code>
     */
    public Builder setUserCmt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userCmt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string user_cmt = 18;</code>
     */
    public Builder clearUserCmt() {
      
      userCmt_ = getDefaultInstance().getUserCmt();
      onChanged();
      return this;
    }
    /**
     * <code>string user_cmt = 18;</code>
     */
    public Builder setUserCmtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userCmt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object buyDate_ = "";
    /**
     * <code>string buy_date = 19;</code>
     */
    public java.lang.String getBuyDate() {
      java.lang.Object ref = buyDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buyDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string buy_date = 19;</code>
     */
    public com.google.protobuf.ByteString
        getBuyDateBytes() {
      java.lang.Object ref = buyDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string buy_date = 19;</code>
     */
    public Builder setBuyDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      buyDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string buy_date = 19;</code>
     */
    public Builder clearBuyDate() {
      
      buyDate_ = getDefaultInstance().getBuyDate();
      onChanged();
      return this;
    }
    /**
     * <code>string buy_date = 19;</code>
     */
    public Builder setBuyDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      buyDate_ = value;
      onChanged();
      return this;
    }

    private int delFlg_ ;
    /**
     * <code>int32 del_flg = 20;</code>
     */
    public int getDelFlg() {
      return delFlg_;
    }
    /**
     * <code>int32 del_flg = 20;</code>
     */
    public Builder setDelFlg(int value) {
      
      delFlg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 del_flg = 20;</code>
     */
    public Builder clearDelFlg() {
      
      delFlg_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object createDate_ = "";
    /**
     * <code>string create_date = 21;</code>
     */
    public java.lang.String getCreateDate() {
      java.lang.Object ref = createDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string create_date = 21;</code>
     */
    public com.google.protobuf.ByteString
        getCreateDateBytes() {
      java.lang.Object ref = createDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string create_date = 21;</code>
     */
    public Builder setCreateDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string create_date = 21;</code>
     */
    public Builder clearCreateDate() {
      
      createDate_ = getDefaultInstance().getCreateDate();
      onChanged();
      return this;
    }
    /**
     * <code>string create_date = 21;</code>
     */
    public Builder setCreateDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updateDate_ = "";
    /**
     * <code>string update_date = 22;</code>
     */
    public java.lang.String getUpdateDate() {
      java.lang.Object ref = updateDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string update_date = 22;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateDateBytes() {
      java.lang.Object ref = updateDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string update_date = 22;</code>
     */
    public Builder setUpdateDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updateDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string update_date = 22;</code>
     */
    public Builder clearUpdateDate() {
      
      updateDate_ = getDefaultInstance().getUpdateDate();
      onChanged();
      return this;
    }
    /**
     * <code>string update_date = 22;</code>
     */
    public Builder setUpdateDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updateDate_ = value;
      onChanged();
      return this;
    }

    private int createId_ ;
    /**
     * <code>int32 create_id = 23;</code>
     */
    public int getCreateId() {
      return createId_;
    }
    /**
     * <code>int32 create_id = 23;</code>
     */
    public Builder setCreateId(int value) {
      
      createId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 create_id = 23;</code>
     */
    public Builder clearCreateId() {
      
      createId_ = 0;
      onChanged();
      return this;
    }

    private int updateId_ ;
    /**
     * <code>int32 update_id = 24;</code>
     */
    public int getUpdateId() {
      return updateId_;
    }
    /**
     * <code>int32 update_id = 24;</code>
     */
    public Builder setUpdateId(int value) {
      
      updateId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 update_id = 24;</code>
     */
    public Builder clearUpdateId() {
      
      updateId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object createPgmId_ = "";
    /**
     * <code>string create_pgm_id = 25;</code>
     */
    public java.lang.String getCreatePgmId() {
      java.lang.Object ref = createPgmId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createPgmId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string create_pgm_id = 25;</code>
     */
    public com.google.protobuf.ByteString
        getCreatePgmIdBytes() {
      java.lang.Object ref = createPgmId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createPgmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string create_pgm_id = 25;</code>
     */
    public Builder setCreatePgmId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createPgmId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string create_pgm_id = 25;</code>
     */
    public Builder clearCreatePgmId() {
      
      createPgmId_ = getDefaultInstance().getCreatePgmId();
      onChanged();
      return this;
    }
    /**
     * <code>string create_pgm_id = 25;</code>
     */
    public Builder setCreatePgmIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createPgmId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updatePgmId_ = "";
    /**
     * <code>string update_pgm_id = 26;</code>
     */
    public java.lang.String getUpdatePgmId() {
      java.lang.Object ref = updatePgmId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatePgmId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string update_pgm_id = 26;</code>
     */
    public com.google.protobuf.ByteString
        getUpdatePgmIdBytes() {
      java.lang.Object ref = updatePgmId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatePgmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string update_pgm_id = 26;</code>
     */
    public Builder setUpdatePgmId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updatePgmId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string update_pgm_id = 26;</code>
     */
    public Builder clearUpdatePgmId() {
      
      updatePgmId_ = getDefaultInstance().getUpdatePgmId();
      onChanged();
      return this;
    }
    /**
     * <code>string update_pgm_id = 26;</code>
     */
    public Builder setUpdatePgmIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updatePgmId_ = value;
      onChanged();
      return this;
    }

    private long version_ ;
    /**
     * <code>int64 version = 27;</code>
     */
    public long getVersion() {
      return version_;
    }
    /**
     * <code>int64 version = 27;</code>
     */
    public Builder setVersion(long value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 version = 27;</code>
     */
    public Builder clearVersion() {
      
      version_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trade.ReplyTrade)
  }

  // @@protoc_insertion_point(class_scope:trade.ReplyTrade)
  private static final grpc.trade.proto.ReplyTrade DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.trade.proto.ReplyTrade();
  }

  public static grpc.trade.proto.ReplyTrade getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplyTrade>
      PARSER = new com.google.protobuf.AbstractParser<ReplyTrade>() {
    public ReplyTrade parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReplyTrade(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplyTrade> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplyTrade> getParserForType() {
    return PARSER;
  }

  public grpc.trade.proto.ReplyTrade getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

