// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tradedtls.proto

package grpc.trade.proto;

public interface ReplyTradeDetailListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trade.ReplyTradeDetailList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  java.util.List<grpc.trade.proto.ReplyTradeDetail> 
      getTradeDetailListList();
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  grpc.trade.proto.ReplyTradeDetail getTradeDetailList(int index);
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  int getTradeDetailListCount();
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  java.util.List<? extends grpc.trade.proto.ReplyTradeDetailOrBuilder> 
      getTradeDetailListOrBuilderList();
  /**
   * <code>repeated .trade.ReplyTradeDetail tradeDetailList = 1;</code>
   */
  grpc.trade.proto.ReplyTradeDetailOrBuilder getTradeDetailListOrBuilder(
      int index);
}
