// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package grpc.trade.proto;

public interface ReplyTradeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trade.ReplyTrade)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 clid = 2;</code>
   */
  long getClid();

  /**
   * <code>int64 trade_no = 3;</code>
   */
  long getTradeNo();

  /**
   * <code>string destination_name = 4;</code>
   */
  java.lang.String getDestinationName();
  /**
   * <code>string destination_name = 4;</code>
   */
  com.google.protobuf.ByteString
      getDestinationNameBytes();

  /**
   * <code>string destination_name_kana = 5;</code>
   */
  java.lang.String getDestinationNameKana();
  /**
   * <code>string destination_name_kana = 5;</code>
   */
  com.google.protobuf.ByteString
      getDestinationNameKanaBytes();

  /**
   * <code>string destination_zip = 6;</code>
   */
  java.lang.String getDestinationZip();
  /**
   * <code>string destination_zip = 6;</code>
   */
  com.google.protobuf.ByteString
      getDestinationZipBytes();

  /**
   * <code>string destination_address = 7;</code>
   */
  java.lang.String getDestinationAddress();
  /**
   * <code>string destination_address = 7;</code>
   */
  com.google.protobuf.ByteString
      getDestinationAddressBytes();

  /**
   * <code>string destination_tel = 8;</code>
   */
  java.lang.String getDestinationTel();
  /**
   * <code>string destination_tel = 8;</code>
   */
  com.google.protobuf.ByteString
      getDestinationTelBytes();

  /**
   * <code>string destination_daytime_conadr = 9;</code>
   */
  java.lang.String getDestinationDaytimeConadr();
  /**
   * <code>string destination_daytime_conadr = 9;</code>
   */
  com.google.protobuf.ByteString
      getDestinationDaytimeConadrBytes();

  /**
   * <code>string destination_store_cd = 10;</code>
   */
  java.lang.String getDestinationStoreCd();
  /**
   * <code>string destination_store_cd = 10;</code>
   */
  com.google.protobuf.ByteString
      getDestinationStoreCdBytes();

  /**
   * <code>string destination_name_edit = 11;</code>
   */
  java.lang.String getDestinationNameEdit();
  /**
   * <code>string destination_name_edit = 11;</code>
   */
  com.google.protobuf.ByteString
      getDestinationNameEditBytes();

  /**
   * <code>string destination_address_edit = 12;</code>
   */
  java.lang.String getDestinationAddressEdit();
  /**
   * <code>string destination_address_edit = 12;</code>
   */
  com.google.protobuf.ByteString
      getDestinationAddressEditBytes();

  /**
   * <code>string destination_tel_edit = 13;</code>
   */
  java.lang.String getDestinationTelEdit();
  /**
   * <code>string destination_tel_edit = 13;</code>
   */
  com.google.protobuf.ByteString
      getDestinationTelEditBytes();

  /**
   * <code>string destination_zip_edit = 14;</code>
   */
  java.lang.String getDestinationZipEdit();
  /**
   * <code>string destination_zip_edit = 14;</code>
   */
  com.google.protobuf.ByteString
      getDestinationZipEditBytes();

  /**
   * <code>string destination_daytime_conadr_edit = 15;</code>
   */
  java.lang.String getDestinationDaytimeConadrEdit();
  /**
   * <code>string destination_daytime_conadr_edit = 15;</code>
   */
  com.google.protobuf.ByteString
      getDestinationDaytimeConadrEditBytes();

  /**
   * <code>string destination_name_kana_edit = 16;</code>
   */
  java.lang.String getDestinationNameKanaEdit();
  /**
   * <code>string destination_name_kana_edit = 16;</code>
   */
  com.google.protobuf.ByteString
      getDestinationNameKanaEditBytes();

  /**
   * <code>string destination_store_cd_edit = 17;</code>
   */
  java.lang.String getDestinationStoreCdEdit();
  /**
   * <code>string destination_store_cd_edit = 17;</code>
   */
  com.google.protobuf.ByteString
      getDestinationStoreCdEditBytes();

  /**
   * <code>string user_cmt = 18;</code>
   */
  java.lang.String getUserCmt();
  /**
   * <code>string user_cmt = 18;</code>
   */
  com.google.protobuf.ByteString
      getUserCmtBytes();

  /**
   * <code>string buy_date = 19;</code>
   */
  java.lang.String getBuyDate();
  /**
   * <code>string buy_date = 19;</code>
   */
  com.google.protobuf.ByteString
      getBuyDateBytes();

  /**
   * <code>int32 del_flg = 20;</code>
   */
  int getDelFlg();

  /**
   * <code>string create_date = 21;</code>
   */
  java.lang.String getCreateDate();
  /**
   * <code>string create_date = 21;</code>
   */
  com.google.protobuf.ByteString
      getCreateDateBytes();

  /**
   * <code>string update_date = 22;</code>
   */
  java.lang.String getUpdateDate();
  /**
   * <code>string update_date = 22;</code>
   */
  com.google.protobuf.ByteString
      getUpdateDateBytes();

  /**
   * <code>int32 create_id = 23;</code>
   */
  int getCreateId();

  /**
   * <code>int32 update_id = 24;</code>
   */
  int getUpdateId();

  /**
   * <code>string create_pgm_id = 25;</code>
   */
  java.lang.String getCreatePgmId();
  /**
   * <code>string create_pgm_id = 25;</code>
   */
  com.google.protobuf.ByteString
      getCreatePgmIdBytes();

  /**
   * <code>string update_pgm_id = 26;</code>
   */
  java.lang.String getUpdatePgmId();
  /**
   * <code>string update_pgm_id = 26;</code>
   */
  com.google.protobuf.ByteString
      getUpdatePgmIdBytes();

  /**
   * <code>int64 version = 27;</code>
   */
  long getVersion();
}
