// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tradedtls.proto

package grpc.trade.proto;

public interface RequestTradeIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trade.RequestTradeId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 tradeId = 1;</code>
   */
  java.util.List<java.lang.Long> getTradeIdList();
  /**
   * <code>repeated int64 tradeId = 1;</code>
   */
  int getTradeIdCount();
  /**
   * <code>repeated int64 tradeId = 1;</code>
   */
  long getTradeId(int index);
}
