// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package grpc.trade.proto;

public interface RequestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trade.RequestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
