// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tradedtls.proto

package grpc.trade.proto;

/**
 * Protobuf type {@code trade.RequestTradeId}
 */
public  final class RequestTradeId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trade.RequestTradeId)
    RequestTradeIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestTradeId.newBuilder() to construct.
  private RequestTradeId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestTradeId() {
    tradeId_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestTradeId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              tradeId_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            tradeId_.add(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              tradeId_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              tradeId_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        tradeId_ = java.util.Collections.unmodifiableList(tradeId_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.trade.proto.TradeDetailProto.internal_static_trade_RequestTradeId_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.trade.proto.TradeDetailProto.internal_static_trade_RequestTradeId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.trade.proto.RequestTradeId.class, grpc.trade.proto.RequestTradeId.Builder.class);
  }

  public static final int TRADEID_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Long> tradeId_;
  /**
   * <code>repeated int64 tradeId = 1;</code>
   */
  public java.util.List<java.lang.Long>
      getTradeIdList() {
    return tradeId_;
  }
  /**
   * <code>repeated int64 tradeId = 1;</code>
   */
  public int getTradeIdCount() {
    return tradeId_.size();
  }
  /**
   * <code>repeated int64 tradeId = 1;</code>
   */
  public long getTradeId(int index) {
    return tradeId_.get(index);
  }
  private int tradeIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getTradeIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(tradeIdMemoizedSerializedSize);
    }
    for (int i = 0; i < tradeId_.size(); i++) {
      output.writeInt64NoTag(tradeId_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < tradeId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(tradeId_.get(i));
      }
      size += dataSize;
      if (!getTradeIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      tradeIdMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.trade.proto.RequestTradeId)) {
      return super.equals(obj);
    }
    grpc.trade.proto.RequestTradeId other = (grpc.trade.proto.RequestTradeId) obj;

    boolean result = true;
    result = result && getTradeIdList()
        .equals(other.getTradeIdList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTradeIdCount() > 0) {
      hash = (37 * hash) + TRADEID_FIELD_NUMBER;
      hash = (53 * hash) + getTradeIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.trade.proto.RequestTradeId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.trade.proto.RequestTradeId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.RequestTradeId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.trade.proto.RequestTradeId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.trade.proto.RequestTradeId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trade.RequestTradeId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trade.RequestTradeId)
      grpc.trade.proto.RequestTradeIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.trade.proto.TradeDetailProto.internal_static_trade_RequestTradeId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.trade.proto.TradeDetailProto.internal_static_trade_RequestTradeId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.trade.proto.RequestTradeId.class, grpc.trade.proto.RequestTradeId.Builder.class);
    }

    // Construct using grpc.trade.proto.RequestTradeId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      tradeId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.trade.proto.TradeDetailProto.internal_static_trade_RequestTradeId_descriptor;
    }

    public grpc.trade.proto.RequestTradeId getDefaultInstanceForType() {
      return grpc.trade.proto.RequestTradeId.getDefaultInstance();
    }

    public grpc.trade.proto.RequestTradeId build() {
      grpc.trade.proto.RequestTradeId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.trade.proto.RequestTradeId buildPartial() {
      grpc.trade.proto.RequestTradeId result = new grpc.trade.proto.RequestTradeId(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        tradeId_ = java.util.Collections.unmodifiableList(tradeId_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.tradeId_ = tradeId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.trade.proto.RequestTradeId) {
        return mergeFrom((grpc.trade.proto.RequestTradeId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.trade.proto.RequestTradeId other) {
      if (other == grpc.trade.proto.RequestTradeId.getDefaultInstance()) return this;
      if (!other.tradeId_.isEmpty()) {
        if (tradeId_.isEmpty()) {
          tradeId_ = other.tradeId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTradeIdIsMutable();
          tradeId_.addAll(other.tradeId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.trade.proto.RequestTradeId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.trade.proto.RequestTradeId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Long> tradeId_ = java.util.Collections.emptyList();
    private void ensureTradeIdIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        tradeId_ = new java.util.ArrayList<java.lang.Long>(tradeId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 tradeId = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getTradeIdList() {
      return java.util.Collections.unmodifiableList(tradeId_);
    }
    /**
     * <code>repeated int64 tradeId = 1;</code>
     */
    public int getTradeIdCount() {
      return tradeId_.size();
    }
    /**
     * <code>repeated int64 tradeId = 1;</code>
     */
    public long getTradeId(int index) {
      return tradeId_.get(index);
    }
    /**
     * <code>repeated int64 tradeId = 1;</code>
     */
    public Builder setTradeId(
        int index, long value) {
      ensureTradeIdIsMutable();
      tradeId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 tradeId = 1;</code>
     */
    public Builder addTradeId(long value) {
      ensureTradeIdIsMutable();
      tradeId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 tradeId = 1;</code>
     */
    public Builder addAllTradeId(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureTradeIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tradeId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 tradeId = 1;</code>
     */
    public Builder clearTradeId() {
      tradeId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trade.RequestTradeId)
  }

  // @@protoc_insertion_point(class_scope:trade.RequestTradeId)
  private static final grpc.trade.proto.RequestTradeId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.trade.proto.RequestTradeId();
  }

  public static grpc.trade.proto.RequestTradeId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestTradeId>
      PARSER = new com.google.protobuf.AbstractParser<RequestTradeId>() {
    public RequestTradeId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestTradeId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestTradeId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestTradeId> getParserForType() {
    return PARSER;
  }

  public grpc.trade.proto.RequestTradeId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

